"""
Seed data for development and testing.
Contains 20 realistic lead samples with various scoring profiles.
"""

from datetime import datetime, timedelta


SEED_LEADS = [
    {
        "email": "alice.johnson@techcorp.io",
        "name": "Alice Johnson",
        "company": "TechCorp Solutions",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=1),
        "pricing_compared": True,
        "lead_through_events": False,
        "lead_through_call": True,
        "lead_through_referral": False,
    },
    {
        "email": "bob.smith@startup.com",
        "name": "Bob Smith",
        "company": "Startup Innovations",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=3),
        "pricing_compared": True,
        "lead_through_events": True,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "carol.white@enterprise.com",
        "name": "Carol White",
        "company": "Enterprise Systems",
        "demo_requested": True,
        "registration": False,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=5),
        "pricing_compared": False,
        "lead_through_events": False,
        "lead_through_call": True,
        "lead_through_referral": True,
    },
    {
        "email": "david.brown@consulting.co",
        "name": "David Brown",
        "company": "Digital Consulting",
        "demo_requested": False,
        "registration": True,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=7),
        "pricing_compared": True,
        "lead_through_events": False,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "emma.davis@growth.inc",
        "name": "Emma Davis",
        "company": "Growth Marketing Inc",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=2),
        "pricing_compared": True,
        "lead_through_events": True,
        "lead_through_call": False,
        "lead_through_referral": True,
    },
    {
        "email": "frank.miller@cloudops.io",
        "name": "Frank Miller",
        "company": "CloudOps Platform",
        "demo_requested": False,
        "registration": True,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=10),
        "pricing_compared": False,
        "lead_through_events": True,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "grace.lee@fintech.dev",
        "name": "Grace Lee",
        "company": "FinTech Developers",
        "demo_requested": True,
        "registration": False,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=15),
        "pricing_compared": True,
        "lead_through_events": False,
        "lead_through_call": True,
        "lead_through_referral": False,
    },
    {
        "email": "henry.wilson@saas.tech",
        "name": "Henry Wilson",
        "company": "SaaS Technologies",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=4),
        "pricing_compared": True,
        "lead_through_events": False,
        "lead_through_call": True,
        "lead_through_referral": True,
    },
    {
        "email": "iris.martinez@agency.co",
        "name": "Iris Martinez",
        "company": "Digital Agency Co",
        "demo_requested": False,
        "registration": False,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=20),
        "pricing_compared": False,
        "lead_through_events": True,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "jack.taylor@analytics.io",
        "name": "Jack Taylor",
        "company": "Analytics Pro",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=6),
        "pricing_compared": True,
        "lead_through_events": False,
        "lead_through_call": False,
        "lead_through_referral": True,
    },
    {
        "email": "karen.anderson@webdev.com",
        "name": "Karen Anderson",
        "company": "WebDev Solutions",
        "demo_requested": False,
        "registration": True,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=12),
        "pricing_compared": False,
        "lead_through_events": False,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "liam.thomas@marketing.pro",
        "name": "Liam Thomas",
        "company": "Marketing Pro",
        "demo_requested": True,
        "registration": False,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=8),
        "pricing_compared": False,
        "lead_through_events": True,
        "lead_through_call": True,
        "lead_through_referral": False,
    },
    {
        "email": "mia.jackson@ecommerce.io",
        "name": "Mia Jackson",
        "company": "ECommerce Platform",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=1),
        "pricing_compared": True,
        "lead_through_events": False,
        "lead_through_call": False,
        "lead_through_referral": True,
    },
    {
        "email": "noah.harris@enterprise.net",
        "name": "Noah Harris",
        "company": "Enterprise Solutions",
        "demo_requested": False,
        "registration": False,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=25),
        "pricing_compared": False,
        "lead_through_events": False,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "olivia.martin@crm.app",
        "name": "Olivia Martin",
        "company": "CRM Experts",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=3),
        "pricing_compared": True,
        "lead_through_events": True,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "peter.robinson@devops.cloud",
        "name": "Peter Robinson",
        "company": "DevOps Cloud",
        "demo_requested": False,
        "registration": True,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=9),
        "pricing_compared": False,
        "lead_through_events": False,
        "lead_through_call": True,
        "lead_through_referral": False,
    },
    {
        "email": "quinn.clark@startup.ai",
        "name": "Quinn Clark",
        "company": "Startup AI Inc",
        "demo_requested": True,
        "registration": False,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=2),
        "pricing_compared": True,
        "lead_through_events": True,
        "lead_through_call": True,
        "lead_through_referral": False,
    },
    {
        "email": "rachel.hall@automation.io",
        "name": "Rachel Hall",
        "company": "Automation Solutions",
        "demo_requested": False,
        "registration": False,
        "enquiry_call_whatsapp": False,
        "enquiry_date": datetime.utcnow() - timedelta(days=30),
        "pricing_compared": False,
        "lead_through_events": True,
        "lead_through_call": False,
        "lead_through_referral": False,
    },
    {
        "email": "steve.cooper@mobile.dev",
        "name": "Steve Cooper",
        "company": "Mobile Developers",
        "demo_requested": True,
        "registration": True,
        "enquiry_call_whatsapp": True,
        "enquiry_date": datetime.utcnow() - timedelta(days=0),
        "pricing_compared": True,
        "lead_through_events": False,
        "lead_through_call": True,
        "lead_through_referral": True,
    },
]
